### ISSUE TITLE
Use docs generate proto web CRUD code error

### ISSUE THREAD

**Issue by Kabochar** [zhufuyi/sponge_doc#1]
Error info
```shell
$ sponge web dao \
>   --db-dsn="root:root@(127.0.0.1:3306)/school" \
>   --db-table=teacher \
>   --include-init-db=true \
>   --out=./edusys
Error: required flag(s) "module-name" not set, use "sponge web dao -h" for help
```
docs error description

![image](https://github.com/zhufuyi/sponge_doc/assets/38752750/82497360-fa2f-4cfc-9b97-5b306b168d4b)

When is can run with this command，add `--module-name=edusys` config just ok
```
$ sponge web dao \
>   --db-dsn="demo:demo@(127.0.0.1:13307)/school" \
>   --db-table=teacher \
>   --include-init-db=true \
>   --module-name=edusys \
>   --out=./edusys 
generate 'dao' codes successfully, out = ./
help for use:
        Move the code to the web or rpc project folder.
```

**Comment by zhufuyi** [comment]
The command must specify the `--module-name=edusys` condition:
- there is no `--out` parameter. 
- if the `--out` parameter is present, the edusys directory itself is empty or is not a service directory created by sponge.

This condition is set to make the command simpler and error-free, and should be explained in the documentation.

There is no need to add `-module-name=edusys` here, the default is to read the module-name from `docs/gen.info`, if sponge can read the module-name from that file, it is not valid to specify the module-name parameter manually.

**Comment by Kabochar** [comment]
Gotcha, thank you for reply.
